name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_lines: yes
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 14
          plugin_languages_limit: 6
          commits_authoring: nikos.epping@protonmail.com, nikos.epping@w-hs.de, n.epping@evosec.de
          
          plugin_followup: yes
          plugin_followup_sections: user
          
