name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_lines: yes
          plugin_languages: yes
          plugin_notable: yes
          plugin_languages_limit: 8
          plugin_followup: yes
